Resolve pytest warnings (#245)
Summary:
- Renam `test_character` to avoid Pytest’s collection warning.
- Switch `gradcheck` inputs to double precision (`float64`) to silence related warnings.

```
.:0
.:0
  :0: PytestCollectionWarning: cannot collect 'test_character' because it is not a function.

pymomentum/test/test_blend_shape.py::TestBlendShape::test_diffApplyBlendCoeffs
  C:\Users\jeongseok\dev\momentum\main\.pixi\envs\gpu\Lib\site-packages\torch\autograd\gradcheck.py:922: UserWarning: Input #0 requires gradient and is not a double precision floating point or complex. This check will likely fail if all the inputs are not of double precision floating point or complex.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

## Checklist:

- [x] Adheres to the [style guidelines](https://facebookincubator.github.io/momentum/docs/developer_guide/style_guide)
- [ ] Codebase formatted by running `pixi run lint`


Test Plan:
Run pytest, confirming no warnings:

```
pixi run test_py
```

Reviewed By: nickyhe-gemini

Differential Revision: D71936818

Pulled By: jeongseok-meta