Fix build with fmt 11 (#95)
Summary:
- fmt 11 requires building with /utf-8 for MSVC, otherwise it will result in a build error:
   ```
   D:\a\momentum\momentum\.pixi\envs\default\Library\include\fmt\base.h(458,28): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8' [D:\a\momentum\momentum\build\simd_test.vcxproj]
   ```
- Remove unnecessary version constraints of dependencies in pixi.toml, as the build error was not caught due to fmt being constrained to version 10.
- Update the pixi lock file
- Print more info in CMake log

   ```
   1>-- [ Build Tools ]
   1>-- - CMake               : 3.30.4
   1>-- - CMake Generator     : Visual Studio 17 2022
   1>-- - C Compiler          : MSVC 19.41.34120.0
   1>-- - C++ Compiler        : MSVC 19.41.34120.0
   1>-- - CMake Toolchain File:
   1>--
   1>-- [ CMake Variables ]
   1>-- CMAKE_C_FLAGS:
   1>--   - /DWIN32
   1>--   - /D_WINDOWS
   1>-- CMAKE_CXX_FLAGS:
   1>--   - /DWIN32
   1>--   - /D_WINDOWS
   1>--   - /GR
   1>--   - /EHsc
   1>-- CMAKE_CUDA_FLAGS: (not set)
   ```

## Checklist:

- [x] Adheres to the [style guidelines](https://facebookincubator.github.io/momentum/docs/developer_guide/style_guide)
- [x] Codebase formatted by running `pixi run lint`

Pull Request resolved: https://github.com/facebookincubator/momentum/pull/95

Test Plan:
```
pixi run test
```

Reviewed By: yutingye

Differential Revision: D63944026

Pulled By: jeongseok-meta

fbshipit-source-id: d0378da180222d912001ddb7bf01d3c6c5b7659b